# Spring配置
spring:
  profiles:
    # 开启使用配置文件，默认是开发环境 druid，部署线上使用 prod
    active: druid
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  10MB
       # 设置总上传的文件大小
       max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

# token配置
token:
    # 令牌自定义标识
    header: Authorization
    # 令牌密钥
    secret: baseframeabcdefghijklmnopq
    # 令牌有效期（默认30分钟）
    expireTime: 30
    # 手机端令牌有效期（默认7天分钟） 7天
    mobileExpireTime: 1440
# MyBatis配置
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.ystms.okr.**.domain
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mapper/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper: 
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
