# 项目相关配置
yunsite:
    # 名称
    name: ystiasp
    # 版本
    version: 1.0.0
    # 版权年份
    copyrightYear: 2021
    # 实例演示开关
    demoEnabled: false
    # 文件路径 示例（ Windows配置D:/yunsite/uploadPath，Linux配置 /home/yunsite/uploadPath）
    #profile: D:/ystiasp/uploadPath
    profile: /home/apps/uploadPath

    # 获取ip地址开关
    addressEnabled: true
    # 验证码类型 math 数组计算 char 字符验证
    captchaType: math

# 开发环境配置
server:
    # 服务器的HTTP端口，默认为8080
    port: 8080
    servlet:
        # 应用的访问路径
        context-path: /prod-api
    tomcat:
        # tomcat的URI编码
        uri-encoding: UTF-8
        # tomcat最大线程数，默认为200
        max-threads: 800
        # Tomcat启动初始化的线程数，默认值25
        min-spare-threads: 30

# 数据源配置
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
#        driverClassName: com.mysql.jdbc.Driver
        druid:
            # 主库数据源
            master:
                url: jdbc:mysql://localhost:3306/pikachu-okr?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
                username: root
                password: 123456
            # 从库数据源
            slave:
                # 从数据源开关/默认关闭
                enabled: false
                url: 
                username: 
                password: 
            # 初始连接数
            initialSize: 5
            # 最小连接池数量
            minIdle: 10
            # 最大连接池数量
            maxActive: 20
            # 配置获取连接等待超时的时间
            maxWait: 60000
            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            timeBetweenEvictionRunsMillis: 60000
            # 配置一个连接在池中最小生存的时间，单位是毫秒
            minEvictableIdleTimeMillis: 300000
            # 配置一个连接在池中最大生存的时间，单位是毫秒
            maxEvictableIdleTimeMillis: 900000
            # 配置检测连接是否有效
            validationQuery: SELECT 1 FROM DUAL
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            webStatFilter: 
                enabled: true
            statViewServlet:
                enabled: true
                # 设置白名单，不填则允许所有访问
                allow:
                url-pattern: /druid/*
                # 控制台管理用户名和密码
                login-username: 
                login-password: 
            filter:
                stat:
                    enabled: true
                    # 慢SQL记录
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true

    # redis 配置
    redis:
        # 地址
        host: localhost
        # 端口，默认为6379
        port: 6379
        # 数据库索引
        database: 0
        # 密码
        password: yunsite369
        # 连接超时时间
        timeout: 10s
        lettuce:
            pool:
                # 连接池中的最小空闲连接
                min-idle: 0
                # 连接池中的最大空闲连接
                max-idle: 8
                # 连接池的最大数据库连接数
                max-active: 8
                # #连接池最大阻塞等待时间（使用负值表示没有限制）
                max-wait: -1ms

# 日志配置
logging:
    level:
        com.ystms.okr: info
        org.springframework: warn


# Swagger配置
swagger:
    # 是否开启swagger
    enabled: false
    # 请求前缀
    pathMapping: /
    # 文档描述
    apidoc:
        title: 接口文档
        description: 接口文档
        version: 1.0.0
        name: lh
        url: 1
        email: 12

# 防止XSS攻击
xss:
    # 过滤开关
    enabled: true
    # 排除链接（多个用逗号分隔）
    excludes: /mobile/*,
    # 匹配链接
    urlPatterns: /mobile/*,/system/*,/monitor/*,/tool/*,

# 七牛云存储配置
qiniu:
    accessKey:
    secretKey:
    url:
    bucketName:
    #使用的是华南地区


#微信
wx:
  # 小程序配置
  ma:
    AppId:
    AppSecret:
    # 服务通知模板id
    templateId:
  pay:
    mchId:
    mchKey:
    notifyUrl:
    keyPath: